-- Step 18.6's Audit requirement (Generated By / Generated Date / Download Count).
-- Download Count is derived (COUNT of PDF_GENERATED rows), not a separate stored
-- counter - see 045_AlterPrescriptionAudit_AddPdfGeneratedAction.sql's comments.
CREATE OR ALTER PROCEDURE dbo.usp_Prescription_LogPdfGenerated
    @PrescriptionId INT,
    @ChangedBy NVARCHAR(100),
    @DownloadCount INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO dbo.PrescriptionAudit (PrescriptionId, Action, PreviousValues, NewValues, ChangedBy)
    VALUES (@PrescriptionId, 'PDF_GENERATED', NULL, NULL, @ChangedBy);

    SELECT @DownloadCount = COUNT(*)
    FROM dbo.PrescriptionAudit
    WHERE PrescriptionId = @PrescriptionId
      AND Action = 'PDF_GENERATED';
END
GO
