using Prescription.Application.Exceptions;
using Prescription.Application.Repositories;
using Prescription.Domain.Entities;

namespace Prescription.Application.Services;

public class MedicineService : IMedicineService
{
    private readonly IMedicineRepository _medicineRepository;
    private readonly IMedicineFormRepository _medicineFormRepository;
    private readonly IMedicineRouteRepository _medicineRouteRepository;

    public MedicineService(
        IMedicineRepository medicineRepository,
        IMedicineFormRepository medicineFormRepository,
        IMedicineRouteRepository medicineRouteRepository)
    {
        _medicineRepository = medicineRepository;
        _medicineFormRepository = medicineFormRepository;
        _medicineRouteRepository = medicineRouteRepository;
    }

    public async Task<(IEnumerable<(Medicine Medicine, MedicineForm MedicineForm, MedicineRoute MedicineRoute)> Medicines, int TotalCount)> GetMedicinesAsync(
        int page,
        int pageSize,
        string sortBy,
        string sortDirection)
    {
        var normalizedPage = page < 1 ? 1 : page;
        var normalizedPageSize = pageSize is < 1 or > 100 ? 20 : pageSize;

        return await _medicineRepository.GetMedicinesAsync(normalizedPage, normalizedPageSize, sortBy, sortDirection);
    }

    public async Task<(IEnumerable<(Medicine Medicine, MedicineForm MedicineForm, MedicineRoute MedicineRoute)> Medicines, int TotalCount)> SearchMedicinesAsync(
        int page,
        int pageSize,
        string? searchTerm,
        string? medicineFormCode,
        string? medicineRouteCode,
        string? status,
        bool? isControlledDrug,
        string sortBy,
        string sortDirection)
    {
        var normalizedPage = page < 1 ? 1 : page;
        var normalizedPageSize = pageSize is < 1 or > 100 ? 20 : pageSize;

        return await _medicineRepository.SearchMedicinesAsync(
            normalizedPage,
            normalizedPageSize,
            TrimOrNull(searchTerm),
            TrimOrNull(medicineFormCode),
            TrimOrNull(medicineRouteCode),
            TrimOrNull(status),
            isControlledDrug,
            sortBy,
            sortDirection);
    }

    public Task<(Medicine? Medicine, MedicineForm? MedicineForm, MedicineRoute? MedicineRoute)> GetMedicineByIdAsync(int medicineId)
        => _medicineRepository.GetMedicineByIdAsync(medicineId);

    public async Task<(Medicine Medicine, MedicineForm MedicineForm, MedicineRoute MedicineRoute)> CreateMedicineAsync(
        string medicineCode,
        string medicineName,
        string genericName,
        string? brandName,
        string strength,
        string medicineFormCode,
        string medicineRouteCode,
        string? manufacturer,
        string? atcCode,
        bool isControlledDrug,
        string? notes,
        string createdBy)
    {
        medicineCode = ValidateRequired(medicineCode, nameof(medicineCode));
        medicineName = ValidateRequired(medicineName, nameof(medicineName));
        genericName = ValidateRequired(genericName, nameof(genericName));
        strength = ValidateRequired(strength, nameof(strength));
        medicineFormCode = ValidateRequired(medicineFormCode, nameof(medicineFormCode));
        medicineRouteCode = ValidateRequired(medicineRouteCode, nameof(medicineRouteCode));

        brandName = TrimOrNull(brandName);
        manufacturer = TrimOrNull(manufacturer);
        atcCode = TrimOrNull(atcCode);
        notes = TrimOrNull(notes);

        var medicineForm = await GetActiveMedicineFormOrThrowAsync(medicineFormCode);
        var medicineRoute = await GetActiveMedicineRouteOrThrowAsync(medicineRouteCode);

        if (await _medicineRepository.CheckMedicineCodeExistsAsync(medicineCode, excludeMedicineId: null))
        {
            throw new DuplicateMedicineCodeException();
        }

        if (await _medicineRepository.CheckDuplicateMedicineAsync(medicineName, strength, medicineForm.MedicineFormId, excludeMedicineId: null))
        {
            throw new DuplicateMedicineException();
        }

        var newMedicine = new Medicine
        {
            MedicineCode = medicineCode,
            MedicineName = medicineName,
            GenericName = genericName,
            BrandName = brandName,
            Strength = strength,
            MedicineFormId = medicineForm.MedicineFormId,
            MedicineRouteId = medicineRoute.MedicineRouteId,
            Manufacturer = manufacturer,
            ATCCode = atcCode,
            IsControlledDrug = isControlledDrug,
            Notes = notes
        };

        var medicineId = await _medicineRepository.CreateMedicineAsync(newMedicine, createdBy);

        // Re-fetch rather than returning `newMedicine` as-is: CreatedDate and RowVersion
        // are generated by SQL Server, not known to this in-memory object - matches
        // PatientService.CreatePatientAsync's identical reasoning.
        var (createdMedicine, createdForm, createdRoute) = await _medicineRepository.GetMedicineByIdAsync(medicineId);

        return (createdMedicine!, createdForm!, createdRoute!);
    }

    public async Task<(Medicine Medicine, MedicineForm MedicineForm, MedicineRoute MedicineRoute)> UpdateMedicineAsync(
        int medicineId,
        string medicineName,
        string genericName,
        string? brandName,
        string strength,
        string medicineFormCode,
        string medicineRouteCode,
        string? manufacturer,
        string? atcCode,
        bool isControlledDrug,
        string? notes,
        byte[] rowVersion,
        string updatedBy)
    {
        medicineName = ValidateRequired(medicineName, nameof(medicineName));
        genericName = ValidateRequired(genericName, nameof(genericName));
        strength = ValidateRequired(strength, nameof(strength));
        medicineFormCode = ValidateRequired(medicineFormCode, nameof(medicineFormCode));
        medicineRouteCode = ValidateRequired(medicineRouteCode, nameof(medicineRouteCode));

        brandName = TrimOrNull(brandName);
        manufacturer = TrimOrNull(manufacturer);
        atcCode = TrimOrNull(atcCode);
        notes = TrimOrNull(notes);

        var (existingMedicine, _, _) = await _medicineRepository.GetMedicineByIdAsync(medicineId);
        if (existingMedicine is null)
        {
            throw new MedicineNotFoundException();
        }

        var medicineForm = await GetActiveMedicineFormOrThrowAsync(medicineFormCode);
        var medicineRoute = await GetActiveMedicineRouteOrThrowAsync(medicineRouteCode);

        if (await _medicineRepository.CheckDuplicateMedicineAsync(medicineName, strength, medicineForm.MedicineFormId, excludeMedicineId: medicineId))
        {
            throw new DuplicateMedicineException();
        }

        // MedicineCode is deliberately absent from this method's parameters - it cannot
        // be changed after creation (business spec section 5.5) and there is no way to
        // pass one in; IsActive changes only through ActivateMedicineAsync/
        // DeactivateMedicineAsync, matching usp_Medicine_Update's own parameter list.
        var medicineToUpdate = new Medicine
        {
            MedicineId = medicineId,
            MedicineName = medicineName,
            GenericName = genericName,
            BrandName = brandName,
            Strength = strength,
            MedicineFormId = medicineForm.MedicineFormId,
            MedicineRouteId = medicineRoute.MedicineRouteId,
            Manufacturer = manufacturer,
            ATCCode = atcCode,
            IsControlledDrug = isControlledDrug,
            Notes = notes,
            RowVersion = rowVersion
        };

        // The repository/stored procedure is the authoritative check for the RowVersion
        // match - a stale value throws MedicineConcurrencyConflictException from there,
        // not here (mirrors PatientService.UpdatePatientAsync).
        await _medicineRepository.UpdateMedicineAsync(medicineToUpdate, updatedBy);

        var (updatedMedicine, updatedForm, updatedRoute) = await _medicineRepository.GetMedicineByIdAsync(medicineId);

        return (updatedMedicine!, updatedForm!, updatedRoute!);
    }

    public async Task<(Medicine Medicine, MedicineForm MedicineForm, MedicineRoute MedicineRoute)> ActivateMedicineAsync(int medicineId, string updatedBy)
    {
        // usp_Medicine_Activate itself throws MEDICINE_NOT_FOUND (translated to
        // MedicineNotFoundException by the repository) when @@ROWCOUNT is 0 - no
        // redundant existence pre-check here, matching PatientService.ActivatePatientAsync.
        await _medicineRepository.ActivateMedicineAsync(medicineId, updatedBy);

        var (medicine, form, route) = await _medicineRepository.GetMedicineByIdAsync(medicineId);

        return (medicine!, form!, route!);
    }

    public async Task<(Medicine Medicine, MedicineForm MedicineForm, MedicineRoute MedicineRoute)> DeactivateMedicineAsync(int medicineId, string updatedBy)
    {
        await _medicineRepository.DeactivateMedicineAsync(medicineId, updatedBy);

        var (medicine, form, route) = await _medicineRepository.GetMedicineByIdAsync(medicineId);

        return (medicine!, form!, route!);
    }

    private async Task<MedicineForm> GetActiveMedicineFormOrThrowAsync(string medicineFormCode)
    {
        var forms = await _medicineFormRepository.GetAllAsync();
        var matchedForm = forms.FirstOrDefault(form =>
            form.IsActive && string.Equals(form.Code, medicineFormCode, StringComparison.OrdinalIgnoreCase));

        return matchedForm ?? throw new InvalidMedicineFormException();
    }

    private async Task<MedicineRoute> GetActiveMedicineRouteOrThrowAsync(string medicineRouteCode)
    {
        var routes = await _medicineRouteRepository.GetAllAsync();
        var matchedRoute = routes.FirstOrDefault(route =>
            route.IsActive && string.Equals(route.Code, medicineRouteCode, StringComparison.OrdinalIgnoreCase));

        return matchedRoute ?? throw new InvalidMedicineRouteException();
    }

    private static string ValidateRequired(string value, string fieldName)
    {
        var trimmed = value?.Trim();

        if (string.IsNullOrWhiteSpace(trimmed))
        {
            throw new ArgumentException($"{fieldName} is required.", fieldName);
        }

        return trimmed;
    }

    private static string? TrimOrNull(string? value)
    {
        var trimmed = value?.Trim();
        return string.IsNullOrEmpty(trimmed) ? null : trimmed;
    }
}
