using System.Security.Cryptography;
using Microsoft.AspNetCore.Identity;
using Prescription.Application.Exceptions;
using Prescription.Application.Repositories;
using Prescription.Domain.Entities;

namespace Prescription.Application.Services;

public class UserService : IUserService
{
    private const int TemporaryPasswordLength = 12;
    private const string TemporaryPasswordAlphabet = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%";

    private readonly IUserRepository _userRepository;
    private readonly IRoleRepository _roleRepository;
    private readonly IPasswordHasher<UserAccount> _passwordHasher;

    public UserService(
        IUserRepository userRepository,
        IRoleRepository roleRepository,
        IPasswordHasher<UserAccount> passwordHasher)
    {
        _userRepository = userRepository;
        _roleRepository = roleRepository;
        _passwordHasher = passwordHasher;
    }

    public async Task<(IEnumerable<(UserAccount UserAccount, Role Role)> Users, int TotalCount)> GetUsersAsync(
        int page,
        int pageSize,
        string? searchTerm,
        string? roleCode,
        string? status,
        string sortBy,
        string sortDirection)
    {
        var normalizedPage = page < 1 ? 1 : page;
        var normalizedPageSize = pageSize is < 1 or > 100 ? 20 : pageSize;

        return await _userRepository.GetUsersAsync(
            normalizedPage,
            normalizedPageSize,
            searchTerm,
            roleCode,
            status,
            sortBy,
            sortDirection);
    }

    public Task<(UserAccount? UserAccount, Role? Role)> GetUserByIdAsync(int userAccountId)
        => _userRepository.GetUserByIdAsync(userAccountId);

    public async Task<(UserAccount UserAccount, Role Role)> CreateUserAsync(
        string firstName,
        string lastName,
        string username,
        string email,
        string? phoneNumber,
        string roleCode,
        string temporaryPassword,
        bool isActive,
        string createdBy)
    {
        ValidateRequired(firstName, nameof(firstName));
        ValidateRequired(lastName, nameof(lastName));
        ValidateRequired(username, nameof(username));
        ValidateRequired(email, nameof(email));
        ValidateRequired(roleCode, nameof(roleCode));
        ValidateRequired(temporaryPassword, nameof(temporaryPassword));

        var role = await GetActiveRoleOrThrowAsync(roleCode);

        if (await _userRepository.IsUsernameExistsAsync(username, excludeUserAccountId: null))
        {
            throw new DuplicateUsernameException();
        }

        if (await _userRepository.IsEmailExistsAsync(email, excludeUserAccountId: null))
        {
            throw new DuplicateEmailException();
        }

        var newUser = new UserAccount
        {
            FirstName = firstName,
            LastName = lastName,
            FullName = $"{firstName} {lastName}",
            Username = username,
            Email = email,
            PhoneNumber = phoneNumber,
            RoleId = role.RoleId,
            IsActive = isActive,
            MustChangePassword = true
        };

        newUser.PasswordHash = _passwordHasher.HashPassword(newUser, temporaryPassword);

        var userAccountId = await _userRepository.CreateUserAsync(newUser, createdBy);

        // Re-fetch rather than returning `newUser` as-is: CreatedDate and RowVersion are
        // generated by SQL Server, not known to this in-memory object - the caller needs
        // the real RowVersion to make any subsequent Update call succeed.
        var (createdUser, createdRole) = await _userRepository.GetUserByIdAsync(userAccountId);

        return (createdUser!, createdRole!);
    }

    public async Task<(UserAccount UserAccount, Role Role)> UpdateUserAsync(
        int userAccountId,
        string firstName,
        string lastName,
        string email,
        string? phoneNumber,
        string roleCode,
        bool isActive,
        byte[] rowVersion,
        string updatedBy)
    {
        ValidateRequired(firstName, nameof(firstName));
        ValidateRequired(lastName, nameof(lastName));
        ValidateRequired(email, nameof(email));
        ValidateRequired(roleCode, nameof(roleCode));

        var (existingUser, _) = await _userRepository.GetUserByIdAsync(userAccountId);
        if (existingUser is null)
        {
            throw new UserNotFoundException();
        }

        var role = await GetActiveRoleOrThrowAsync(roleCode);

        if (await _userRepository.IsEmailExistsAsync(email, excludeUserAccountId: userAccountId))
        {
            throw new DuplicateEmailException();
        }

        // Username is deliberately absent from this method's parameters - it's not
        // merely ignored if supplied, there is no way to pass one in, since it cannot
        // be changed after creation (business spec section 5.5/section 6).
        var userToUpdate = new UserAccount
        {
            UserAccountId = userAccountId,
            FirstName = firstName,
            LastName = lastName,
            Email = email,
            PhoneNumber = phoneNumber,
            RoleId = role.RoleId,
            IsActive = isActive,
            RowVersion = rowVersion
        };

        // The repository/stored procedure is the authoritative check for the RowVersion
        // match - a stale value throws ConcurrencyConflictException from there, not here.
        await _userRepository.UpdateUserAsync(userToUpdate, updatedBy);

        var (updatedUser, updatedRole) = await _userRepository.GetUserByIdAsync(userAccountId);

        return (updatedUser!, updatedRole!);
    }

    public async Task<(UserAccount UserAccount, Role Role)> ActivateUserAsync(int userAccountId, string updatedBy)
    {
        await _userRepository.ActivateUserAsync(userAccountId, updatedBy);

        var (user, role) = await _userRepository.GetUserByIdAsync(userAccountId);

        return (user!, role!);
    }

    public async Task<(UserAccount UserAccount, Role Role)> DeactivateUserAsync(
        int userAccountId,
        int actingUserAccountId,
        string updatedBy)
    {
        if (userAccountId == actingUserAccountId)
        {
            throw new SelfDeactivationException();
        }

        await _userRepository.DeactivateUserAsync(userAccountId, updatedBy);

        var (user, role) = await _userRepository.GetUserByIdAsync(userAccountId);

        return (user!, role!);
    }

    public async Task<string> ResetPasswordAsync(int userAccountId, string updatedBy)
    {
        var (existingUser, _) = await _userRepository.GetUserByIdAsync(userAccountId);
        if (existingUser is null)
        {
            throw new UserNotFoundException();
        }

        var temporaryPassword = GenerateTemporaryPassword();
        var passwordHash = _passwordHasher.HashPassword(existingUser, temporaryPassword);

        await _userRepository.ResetPasswordAsync(userAccountId, passwordHash, updatedBy);

        return temporaryPassword;
    }

    private async Task<Role> GetActiveRoleOrThrowAsync(string roleCode)
    {
        var activeRoles = await _roleRepository.GetAllActiveRolesAsync();
        var matchedRole = activeRoles.FirstOrDefault(role => string.Equals(role.Code, roleCode, StringComparison.OrdinalIgnoreCase));

        return matchedRole ?? throw new InvalidRoleException();
    }

    private static void ValidateRequired(string value, string fieldName)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            throw new ArgumentException($"{fieldName} is required.", fieldName);
        }
    }

    private static string GenerateTemporaryPassword()
    {
        var randomBytes = new byte[TemporaryPasswordLength];
        RandomNumberGenerator.Fill(randomBytes);

        var characters = new char[TemporaryPasswordLength];
        for (var index = 0; index < TemporaryPasswordLength; index++)
        {
            characters[index] = TemporaryPasswordAlphabet[randomBytes[index] % TemporaryPasswordAlphabet.Length];
        }

        return new string(characters);
    }
}
