-- Step 18.6: extends PrescriptionAudit's Action CHECK constraint to allow
-- 'PDF_GENERATED' - logging Generated By/Generated Date for PDF downloads (Step 18.6's
-- own Audit requirement). "Download Count" is deliberately NOT a separate stored
-- counter column - it is derived by counting PDF_GENERATED rows for a given
-- PrescriptionId, keeping PrescriptionAudit the single source of truth rather than
-- risking a denormalized counter drifting out of sync with the log it's supposed to
-- summarize (the same reasoning already applied to every other audit table in this
-- project). CHECK constraints cannot be altered in place in SQL Server - this drops and
-- re-adds it with the same name, guarded so the script is safe to re-run.

IF EXISTS (SELECT 1 FROM sys.check_constraints WHERE name = 'CK_PrescriptionAudit_Action' AND parent_object_id = OBJECT_ID('dbo.PrescriptionAudit'))
BEGIN
    ALTER TABLE dbo.PrescriptionAudit DROP CONSTRAINT CK_PrescriptionAudit_Action;
END
GO

ALTER TABLE dbo.PrescriptionAudit
    ADD CONSTRAINT CK_PrescriptionAudit_Action CHECK (Action IN ('CREATED', 'UPDATED', 'PDF_GENERATED'));
GO
